[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"  # Add this line to specify the functions directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
